### ISSUE TITLE
missing file" Cod.Pringting.pas" when compiling...

### ISSUE THREAD

**Issue by frankwu-delphi** [Codrax/Codrut-Printing#1]
can you pls completed/fix this file?

**Comment by Codrax** [comment]
My mistake, I will include the file as soon as I'm back at my computer.

**Comment by Codrax** [comment]
The updated version of the application includes all the required units and DLLs, also a lot of new features and improvements.

I tested the compilation with only the units I added and everything seems to work perfectly.

Please do note that the Codrut Fluent Design System has also been updated, so you will need the new version.
